import type { ComputeUnit, EnrichedIR } from "../../ir/index.js";
import { renderSections } from "../../render/engine.js";
import { quote, tfName } from "../../render/hcl.js";
import type { RenderResult } from "../../render/types.js";

const HEADER = "# Generated by DoDeploy — review before applying.\n";

const unitImage = (unit: ComputeUnit): string => {
  if (unit.image !== undefined) return quote(unit.image);
  return `var.${tfName(unit.name)}_image # TODO(dodeploy): build & push this image (see ECR recommendation)`;
};

const providersTf = (): string =>
  `${HEADER}
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}
`;

const variablesTf = (ir: EnrichedIR): string => {
  const builderVars = ir.compute
    .filter((u) => u.buildContext !== undefined && u.image === undefined)
    .map(
      (u) => `variable "${tfName(u.name)}_image" {
  type        = string
  description = "Full image URI for ${u.name} (build from ${u.buildContext ?? "context"} and push to ECR)"
}
`,
    )
    .join("\n");
  return `${HEADER}
variable "project_name" {
  type = string
}

variable "region" {
  type = string
}

variable "vpc_cidr" {
  type    = string
  default = "10.0.0.0/16"
}

variable "db_password" {
  type        = string
  sensitive   = true
  description = "Master password for managed databases — set via TF_VAR_db_password or a secrets backend"
}

${builderVars}`;
};

const vpcSection = (): string =>
  `resource "aws_vpc" "main" {
  cidr_block           = var.vpc_cidr
  enable_dns_support   = true
  enable_dns_hostnames = true
  tags                 = { Project = var.project_name }
}

resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id
}

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_subnet" "public_a" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = cidrsubnet(var.vpc_cidr, 8, 1)
  availability_zone       = data.aws_availability_zones.available.names[0]
  map_public_ip_on_launch = true
}

resource "aws_subnet" "public_b" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = cidrsubnet(var.vpc_cidr, 8, 2)
  availability_zone       = data.aws_availability_zones.available.names[1]
  map_public_ip_on_launch = true
}

resource "aws_subnet" "private_a" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, 11)
  availability_zone = data.aws_availability_zones.available.names[0]
}

resource "aws_subnet" "private_b" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, 12)
  availability_zone = data.aws_availability_zones.available.names[1]
}`;

const albSection = (ir: EnrichedIR): string => {
  const webUnits = ir.compute.filter((u) => u.kind === "web" && u.ports.some((p) => p.public));
  if (webUnits.length === 0) return "";
  const first = webUnits[0];
  if (first === undefined) return "";
  const targetGroups = webUnits
    .map((u) => {
      const port = u.ports.find((p) => p.public)?.container ?? 80;
      return `resource "aws_lb_target_group" "${tfName(u.name)}" {
  name        = "${tfName(ir.meta.name)}-${tfName(u.name)}"
  port        = ${port}
  protocol    = "HTTP"
  vpc_id      = aws_vpc.main.id
  target_type = "ip"
}`;
    })
    .join("\n\n");
  return `resource "aws_lb" "main" {
  name               = "${tfName(ir.meta.name)}-alb"
  load_balancer_type = "application"
  subnets            = [aws_subnet.public_a.id, aws_subnet.public_b.id]
}

resource "aws_lb_listener" "http" {
  load_balancer_arn = aws_lb.main.arn
  port              = 80
  protocol          = "HTTP"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.${tfName(first.name)}.arn
  }
}

${targetGroups}`;
};

const sgSection = (ir: EnrichedIR): string => {
  const computeNames = new Set(ir.compute.map((u) => u.name));
  const sgNames = new Set(computeNames);
  for (const rule of ir.network.securityGroupRules) {
    if (!computeNames.has(rule.to)) sgNames.add(rule.to);
  }
  return [...sgNames]
    .map((name) => {
      const label = tfName(name);
      const unit = ir.compute.find((u) => u.name === name);
      const publicPort = unit?.ports.find((p) => p.public)?.container;
      const publicIngress =
        publicPort !== undefined
          ? `
  ingress {
    from_port   = ${publicPort}
    to_port     = ${publicPort}
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }`
          : "";
      const rules = ir.network.securityGroupRules
        .filter((r) => r.to === name)
        .map(
          (r) => `
  ingress {
    from_port       = ${r.port}
    to_port         = ${r.port}
    protocol        = "tcp"
    security_groups = [aws_security_group.${tfName(r.from)}.id]
    description     = ${quote(`${r.from} -> ${r.to}:${r.port}`)}
  }`,
        )
        .join("");
      return `resource "aws_security_group" "${label}" {
  name   = ${quote(label)}
  vpc_id = aws_vpc.main.id
${publicIngress}${rules}

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}`;
    })
    .join("\n\n");
};

const discoverySection = (ir: EnrichedIR): string => {
  if (!ir.network.serviceDiscovery) return "";
  const services = ir.compute
    .map(
      (u) => `resource "aws_service_discovery_service" "${tfName(u.name)}" {
  name         = ${quote(tfName(u.name))}
  namespace_id = aws_service_discovery_http_namespace.main.id
}`,
    )
    .join("\n\n");
  return `resource "aws_service_discovery_http_namespace" "main" {
  name = "${tfName(ir.meta.name)}.local"
}

${services}`;
};

const ecsClusterSection = (): string => `resource "aws_ecs_cluster" "main" {
  name = var.project_name
}`;

const taskDefSection = (ir: EnrichedIR): string =>
  ir.compute
    .filter((u) => u.kind !== "stateful")
    .map((u) => {
      const label = tfName(u.name);
      const cpu = u.cpu !== undefined ? Math.round(u.cpu * 1024) : 512;
      const memory = u.memoryMb ?? 1024;
      const portMappings =
        u.ports.length > 0
          ? `    portMappings = [${u.ports
              .map((p) => `{ containerPort = ${p.container} }`)
              .join(", ")}]`
          : "";
      const envVars = Object.entries(u.env)
        .filter(([key]) => !u.secrets.includes(key))
        .map(([key, value]) => `      { name = ${quote(key)}, value = ${quote(value)} },`)
        .join("\n");
      const environment = envVars.length > 0 ? `    environment = [\n${envVars}\n    ]` : "";
      return `resource "aws_ecs_task_definition" "${label}" {
  family                   = ${quote(label)}
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "${cpu}"
  memory                   = "${memory}"
  container_definitions    = jsonencode([
    {
      name      = ${quote(label)}
      image     = ${unitImage(u)}
      essential = true
${portMappings}
${environment}
    }
  ])
}`;
    })
    .join("\n\n");
const statefulSection = (ir: EnrichedIR): string => {
  const stateful = ir.compute.filter((u) => u.kind === "stateful");
  if (stateful.length === 0) return "";
  throw new Error(
    `stateful service(s) ${stateful.map((u) => `"${u.name}"`).join(", ")}: EC2/ASG rendering is not yet supported by this renderer`,
  );
};

const ecsServiceSection = (ir: EnrichedIR): string =>
  ir.compute
    .filter((u) => u.kind !== "stateful")
    .map((u) => {
      const label = tfName(u.name);
      const publicPort = u.ports.find((p) => p.public);
      const loadBalancer =
        u.kind === "web" && publicPort !== undefined
          ? `
  load_balancer {
    target_group_arn = aws_lb_target_group.${label}.arn
    container_name   = ${quote(label)}
    container_port   = ${publicPort.container}
  }`
          : "";
      const registry = ir.network.serviceDiscovery
        ? `
  service_registries {
    registry_arn = aws_service_discovery_service.${label}.arn
  }`
        : "";
      return `resource "aws_ecs_service" "${label}" {
  name            = ${quote(label)}
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.${label}.arn
  desired_count   = 1
  launch_type     = "FARGATE"

  network_configuration {
    subnets         = [aws_subnet.private_a.id, aws_subnet.private_b.id]
    security_groups = [aws_security_group.${label}.id]
    assign_public_ip = false
  }
${loadBalancer}${registry}
}`;
    })
    .join("\n\n");

const datastoreBlock = (d: EnrichedIR["datastores"][number]): string => {
  const label = tfName(d.name);
  if (d.engine === "postgres" || d.engine === "mysql") {
    return `resource "aws_db_instance" "${label}" {
  identifier           = ${quote(label)}
  engine               = ${quote(d.engine)}
  engine_version       = ${quote(d.version ?? (d.engine === "postgres" ? "16" : "8.0"))}
  instance_class       = "db.t3.micro"
  allocated_storage    = 20
  username             = "dodeploy"
  password             = var.db_password
  skip_final_snapshot  = true
}`;
  }
  if (d.engine === "redis") {
    return `resource "aws_elasticache_cluster" "${label}" {
  cluster_id      = ${quote(label)}
  engine          = "redis"
  node_type       = "cache.t3.micro"
  num_cache_nodes = 1
}`;
  }
  return `resource "aws_docdb_cluster" "${label}" {
  cluster_identifier  = ${quote(label)}
  engine              = "docdb"
  master_username     = "dodeploy"
  master_password     = var.db_password
  skip_final_snapshot = true
}

resource "aws_docdb_cluster_instance" "${label}" {
  cluster_identifier = aws_docdb_cluster.${label}.id
  instance_class     = "db.t3.medium"
}`;
};

const storageBlock = (s: EnrichedIR["storage"][number], ir: EnrichedIR): string => {
  const label = tfName(s.name);
  if (s.kind === "shared-volume" || s.kind === "local-volume") {
    return `resource "aws_efs_file_system" "${label}" {
  creation_token = ${quote(label)}
  tags           = { Name = ${quote(label)} }
}`;
  }
  return `resource "aws_s3_bucket" "${label}" {
  bucket = "${tfName(ir.meta.name)}-${label}"
  tags   = { Project = var.project_name }
}

resource "aws_s3_bucket_public_access_block" "${label}" {
  bucket = aws_s3_bucket.${label}.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}`;
};

const outputsTf = (ir: EnrichedIR): string => {
  const lines: string[] = [];
  if (ir.compute.some((u) => u.kind === "web" && u.ports.some((p) => p.public))) {
    lines.push(`output "alb_dns_name" {
  value = aws_lb.main.dns_name
}`);
  }
  for (const d of ir.datastores) {
    const label = tfName(d.name);
    if (d.engine === "postgres" || d.engine === "mysql") {
      lines.push(`output "db_${label}_address" {
  value = aws_db_instance.${label}.address
}`);
    } else if (d.engine === "redis") {
      lines.push(`output "cache_${label}_address" {
  value = aws_elasticache_cluster.${label}.cache_nodes[0].address
}`);
    } else {
      lines.push(`output "db_${label}_endpoint" {
  value = aws_docdb_cluster.${label}.endpoint
}`);
    }
  }
  for (const s of ir.storage) {
    if (s.kind === "static-assets" || s.kind === "uploads") {
      lines.push(`output "bucket_${tfName(s.name)}" {
  value = aws_s3_bucket.${tfName(s.name)}.bucket
}`);
    }
  }
  return `${HEADER}${lines.join("\n\n")}`;
};

export function renderAws(ir: EnrichedIR): RenderResult {
  const diagnostics: RenderResult["diagnostics"] = [];

  const network = renderSections(
    [
      { name: "vpc", builder: vpcSection },
      { name: "alb", builder: albSection },
      { name: "security-groups", builder: sgSection },
      { name: "service-discovery", builder: discoverySection },
    ],
    ir,
  );
  const compute = renderSections(
    [
      { name: "ecs-cluster", builder: ecsClusterSection },
      { name: "task-definitions", builder: taskDefSection },
      { name: "ecs-services", builder: ecsServiceSection },
      { name: "stateful", builder: statefulSection },
    ],
    ir,
  );
  const data = renderSections(
    [
      ...ir.datastores.map((d) => ({
        name: `datastore-${d.name}`,
        builder: () => datastoreBlock(d),
      })),
      ...ir.storage.map((s) => ({ name: `storage-${s.name}`, builder: () => storageBlock(s, ir) })),
    ],
    ir,
  );

  diagnostics.push(...network.diagnostics, ...compute.diagnostics, ...data.diagnostics);

  return {
    files: {
      "providers.tf": providersTf(),
      "variables.tf": variablesTf(ir),
      "network.tf": `${HEADER}${network.content}`,
      "compute.tf": `${HEADER}${compute.content}`,
      "data.tf": `${HEADER}${data.content}`,
      "outputs.tf": outputsTf(ir),
    },
    diagnostics,
  };
}
