import type { ComputeUnit, EnrichedIR } from "../../ir/index.js";
import { renderSections } from "../../render/engine.js";
import { alignFiles, duplicateLabelError, quote, tfName } from "../../render/hcl.js";
import type { RenderResult } from "../../render/types.js";
import { resolveDatabaseVersion } from "../database-version.js";

const HEADER = "# Generated by DoDeploy — review before applying.\n";

// Partition helpers for target-aware rendering.
const fargateUnits = (ir: EnrichedIR) =>
  ir.compute.filter(
    (u) => u.kind !== "stateful" && (u.target === undefined || u.target === "fargate"),
  );

// Supported AWS Fargate task sizes: [cpu units, min memory MiB, max memory MiB]
// https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-tasks-services.html
const FARGATE_SIZES: readonly (readonly [number, number, number])[] = [
  [256, 512, 2048],
  [512, 1024, 4096],
  [1024, 2048, 8192],
  [2048, 4096, 16384],
  [4096, 8192, 30720],
  [8192, 16384, 61440],
  [16384, 32768, 122880],
];

/** Snap requested cpu/memory to the smallest supported Fargate task size. */
const fargateSize = (unit: ComputeUnit): { cpu: number; memory: number; adjustments: string[] } => {
  const wantCpu = unit.cpu !== undefined ? Math.max(1, Math.round(unit.cpu * 1024)) : 512;
  const wantMem = unit.memoryMb ?? 1024;
  const size =
    FARGATE_SIZES.find(([cpu, , max]) => cpu >= wantCpu && wantMem <= max) ??
    FARGATE_SIZES[FARGATE_SIZES.length - 1]!;
  const [cpu, minMem, maxMem] = size;
  const step = cpu >= 8192 ? 4096 : 1024;
  const memory = Math.min(maxMem, Math.max(minMem, Math.round(wantMem / step) * step));
  const adjustments: string[] = [];
  if (cpu !== wantCpu) adjustments.push(`cpu ${wantCpu} → ${cpu}`);
  if (memory !== wantMem) adjustments.push(`memory ${wantMem}MiB → ${memory}MiB`);
  return { cpu, memory, adjustments };
};
const ec2Units = (ir: EnrichedIR) => ir.compute.filter((u) => u.target === "ec2");
const apprunnerUnits = (ir: EnrichedIR) => ir.compute.filter((u) => u.target === "apprunner");

// Public web TCP ports are treated as HTTP; the IR has no application protocol.
const publicRoutes = (ir: EnrichedIR) => {
  const ports = fargateUnits(ir).flatMap((unit) =>
    unit.ports.filter((port) => port.public).map((port) => ({ unit, port })),
  );
  return ports
    .filter(
      ({ unit, port }) =>
        unit.kind === "web" &&
        port.protocol === "tcp" &&
        port.host !== undefined &&
        ports.filter((other) => other.port.host === port.host).length === 1 &&
        unit.ports.filter((other) => other.public && other.protocol === "tcp").length <= 5,
    )
    .map(({ unit, port }) => ({
      unit,
      port,
      label: `${tfName(unit.name)}_${port.host}`,
      targetLabel:
        unit.ports.filter((p) => p.public).length === 1
          ? tfName(unit.name)
          : `${tfName(unit.name)}_${port.host}`,
    }));
};

const unitImage = (unit: ComputeUnit): string => {
  if (unit.image !== undefined) return quote(unit.image);
  return `var.${tfName(unit.name)}_image # TODO(dodeploy): build & push this image (see ECR recommendation)`;
};

const providersTf = (): string =>
  `${HEADER}
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}
`;

const variablesTf = (ir: EnrichedIR): string => {
  // Every unit without an image references this variable — declare it whether or
  // not a build context exists (interview-only units have neither).
  const builderVars = ir.compute
    .filter((u) => u.image === undefined)
    .map(
      (u) => `variable "${tfName(u.name)}_image" {
  type        = string
  description = ${quote(
    u.buildContext !== undefined
      ? `Full image URI for ${u.name} (build from ${u.buildContext} and push to ECR)`
      : `Full image URI for ${u.name} — push to ECR and set via TF_VAR_${tfName(u.name)}_image`,
  )}
}
`,
    )
    .join("\n");
  return `${HEADER}
variable "project_name" {
  type    = string
  default = ${quote(ir.meta.name)}
}

variable "region" {
  type    = string
  default = ${quote(ir.meta.region)}
}

variable "vpc_cidr" {
  type    = string
  default = "10.0.0.0/16"
}

variable "db_password" {
  type        = string
  sensitive   = true
  description = "Master password for managed databases — set via TF_VAR_db_password or a secrets backend"
}

${builderVars}`;
};

const vpcSection = (): string =>
  `resource "aws_vpc" "main" {
  cidr_block           = var.vpc_cidr
  enable_dns_support   = true
  enable_dns_hostnames = true
  tags                 = { Project = var.project_name }
}

resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id
}

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_subnet" "public_a" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = cidrsubnet(var.vpc_cidr, 8, 1)
  availability_zone       = data.aws_availability_zones.available.names[0]
  map_public_ip_on_launch = true
}

resource "aws_subnet" "public_b" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = cidrsubnet(var.vpc_cidr, 8, 2)
  availability_zone       = data.aws_availability_zones.available.names[1]
  map_public_ip_on_launch = true
}

resource "aws_subnet" "private_a" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, 11)
  availability_zone = data.aws_availability_zones.available.names[0]
}

resource "aws_subnet" "private_b" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, 12)
  availability_zone = data.aws_availability_zones.available.names[1]
}`;

const routingSection = (): string => `resource "aws_route_table" "public" {
  vpc_id = aws_vpc.main.id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }
}

# NAT gateway incurs hourly and data processing charges, plus cross-AZ transfer for private_b.
# One gateway minimizes baseline cost; use one per AZ when availability requires it.
resource "aws_eip" "nat" {
  domain = "vpc"
}

resource "aws_nat_gateway" "main" {
  allocation_id = aws_eip.nat.id
  subnet_id = aws_subnet.public_a.id
  depends_on = [aws_internet_gateway.main]
}

resource "aws_route_table" "private" {
  vpc_id = aws_vpc.main.id
  route {
    cidr_block = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.main.id
  }
}

${["public_a", "public_b", "private_a", "private_b"]
  .map(
    (subnet) => `resource "aws_route_table_association" "${subnet}" {
  subnet_id = aws_subnet.${subnet}.id
  route_table_id = aws_route_table.${subnet.startsWith("public") ? "public" : "private"}.id
}`,
  )
  .join("\n\n")}`;

const albSection = (ir: EnrichedIR): string => {
  const routes = publicRoutes(ir);
  if (routes.length === 0) return "";
  return `# Public web TCP ports are assumed to serve HTTP; verify application protocol before applying.
resource "aws_security_group" "alb" {
  name = "${tfName(ir.meta.name)}-alb"
  vpc_id = aws_vpc.main.id
${routes
  .map(
    ({ port }) => `
  ingress {
    from_port = ${port.host}
    to_port = ${port.host}
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }`,
  )
  .join("")}
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_lb" "main" {
  name               = "${tfName(ir.meta.name)}-alb"
  load_balancer_type = "application"
  security_groups   = [aws_security_group.alb.id]
  subnets            = [aws_subnet.public_a.id, aws_subnet.public_b.id]
  depends_on         = [aws_route_table_association.public_a, aws_route_table_association.public_b]
}

${routes
  .map(
    ({ port, label, targetLabel }) => `resource "aws_lb_target_group" "${targetLabel}" {
  name_prefix = "dd-"
  port = ${port.container}
  protocol = "HTTP"
  vpc_id = aws_vpc.main.id
  target_type = "ip"
}

resource "aws_lb_listener" "${label}" {
  load_balancer_arn = aws_lb.main.arn
  port = ${port.host}
  protocol = "HTTP"
  default_action {
    type = "forward"
    target_group_arn = aws_lb_target_group.${targetLabel}.arn
  }
}`,
  )
  .join("\n\n")}`;
};

const sgSection = (ir: EnrichedIR): string => {
  const names = new Set([
    ...ir.compute.map((u) => u.name),
    ...ir.datastores.map((d) => d.name),
    ...ir.network.securityGroupRules.flatMap((r) => [r.from, r.to]),
  ]);
  const groups = [...names]
    .map(
      (name) => `resource "aws_security_group" "service_${tfName(name)}" {
  name_prefix = ${quote(`service_${tfName(name)}-`)}
  vpc_id = aws_vpc.main.id
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}`,
    )
    .join("\n\n");
  const ingress = [
    ...publicRoutes(ir).map(({ unit, port }) => ({
      from: "alb",
      to: `service_${tfName(unit.name)}`,
      port: port.container,
    })),
    ...ir.network.securityGroupRules.map((r) => ({
      from: `service_${tfName(r.from)}`,
      to: `service_${tfName(r.to)}`,
      port: r.port,
    })),
  ];
  const uniqueIngress = [
    ...new Map(ingress.map((r) => [`${r.from}|${r.to}|${r.port}`, r])).values(),
  ];
  return `${groups}\n\n${uniqueIngress
    .map(
      (rule, index) => `resource "aws_security_group_rule" "ingress_${index}" {
  type = "ingress"
  from_port = ${rule.port}
  to_port = ${rule.port}
  protocol = "tcp"
  source_security_group_id = aws_security_group.${rule.from}.id
  security_group_id = aws_security_group.${rule.to}.id
}`,
    )
    .join("\n\n")}`;
};

const discoverySection = (ir: EnrichedIR): string => {
  if (!ir.network.serviceDiscovery) return "";
  const services = ir.compute
    .map(
      (u) => `resource "aws_service_discovery_service" "${tfName(u.name)}" {
  name         = ${quote(tfName(u.name))}
  dns_config {
    namespace_id = aws_service_discovery_private_dns_namespace.main.id
    routing_policy = "MULTIVALUE"
    dns_records {
      ttl = 10
      type = "A"
    }
  }
  health_check_custom_config {
    failure_threshold = 1
  }
}`,
    )
    .join("\n\n");
  return `resource "aws_service_discovery_private_dns_namespace" "main" {
  name = "${tfName(ir.meta.name)}.local"
  vpc = aws_vpc.main.id
}

${services}`;
};

const ecsClusterSection = (ir: EnrichedIR): string => {
  if (fargateUnits(ir).length === 0) return "";
  return `data "aws_partition" "current" {}

resource "aws_iam_role" "ecs_execution" {
  name_prefix = "dodeploy-ecs-"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
      Action = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "ecs_execution" {
  role = aws_iam_role.ecs_execution.name
  policy_arn = "arn:\${data.aws_partition.current.partition}:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

resource "aws_ecs_cluster" "main" {
  name = var.project_name
}`;
};

const taskDefSection = (ir: EnrichedIR): string => {
  const units = fargateUnits(ir);
  if (units.length === 0) return "";
  return units
    .map((u) => {
      const label = tfName(u.name);
      const { cpu, memory } = fargateSize(u);
      const portMappings =
        u.ports.length > 0
          ? `      portMappings = [${u.ports
              .filter(
                (port, index) =>
                  u.ports.findIndex(
                    (other) =>
                      other.container === port.container && other.protocol === port.protocol,
                  ) === index,
              )
              .map((p) => `{ containerPort = ${p.container}, protocol = ${quote(p.protocol)} }`)
              .join(", ")}]`
          : "";
      const envVars = Object.entries(u.env)
        .filter(([key]) => !u.secrets.includes(key))
        .map(([key, value]) => `        { name = ${quote(key)}, value = ${quote(value)} },`)
        .join("\n");
      const environment = envVars.length > 0 ? `      environment = [\n${envVars}\n      ]` : "";
      const commandEntry = [
        u.entrypoint !== undefined
          ? `      entryPoint = [${u.entrypoint.map(quote).join(", ")}]`
          : "",
        u.command !== undefined ? `      command    = [${u.command.map(quote).join(", ")}]` : "",
      ]
        .filter(Boolean)
        .join("\n");
      const secretTodo = u.secrets
        .map(
          (key) =>
            `# TODO(dodeploy): ${JSON.stringify(u.name)} secret ${JSON.stringify(key)}: create a Secrets Manager secret manually, add its ARN through container secrets name/valueFrom, and grant the ECS task execution role secretsmanager:GetSecretValue (and kms:Decrypt when required).`,
        )
        .join("\n");
      return `${secretTodo}${secretTodo ? "\n" : ""}resource "aws_ecs_task_definition" "${label}" {
  family                   = ${quote(label)}
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  execution_role_arn = aws_iam_role.ecs_execution.arn
  cpu                      = "${cpu}"
  memory                   = "${memory}"
  container_definitions    = jsonencode([
    {
      name      = ${quote(label)}
      image     = ${unitImage(u)}
      essential = true
${commandEntry ? `${commandEntry}\n` : ""}${portMappings}
${environment}
    }
  ])
}`;
    })
    .join("\n\n");
};
const statefulSection = (ir: EnrichedIR): string => {
  const stateful = ir.compute.filter((u) => u.kind === "stateful");
  if (stateful.length === 0) return "";
  throw new Error(
    `stateful service(s) ${stateful.map((u) => `"${u.name}"`).join(", ")}: EC2/ASG rendering is not yet supported by this renderer`,
  );
};

const ecsServiceSection = (ir: EnrichedIR): string => {
  const units = fargateUnits(ir);
  if (units.length === 0) return "";
  return units
    .map((u) => {
      const label = tfName(u.name);
      const routes = publicRoutes(ir).filter((r) => r.unit.name === u.name);
      const loadBalancer = routes
        .map(
          ({ port, targetLabel }) => `
  load_balancer {
    target_group_arn = aws_lb_target_group.${targetLabel}.arn
    container_name = ${quote(label)}
    container_port = ${port.container}
  }`,
        )
        .join("");
      const registry = ir.network.serviceDiscovery
        ? `
  service_registries {
    registry_arn = aws_service_discovery_service.${label}.arn
  }`
        : "";
      return `resource "aws_ecs_service" "${label}" {
  name            = ${quote(label)}
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.${label}.arn
  desired_count   = 1
  launch_type     = "FARGATE"
  depends_on = [aws_iam_role_policy_attachment.ecs_execution, aws_route_table_association.private_a, aws_route_table_association.private_b${routes.map((route) => `, aws_lb_listener.${route.label}`).join("")}]

  network_configuration {
    subnets         = [aws_subnet.private_a.id, aws_subnet.private_b.id]
    security_groups = [aws_security_group.service_${label}.id]
    assign_public_ip = false
  }
${loadBalancer}${registry}
}`;
    })
    .join("\n\n");
};

const ec2BoxSection = (ir: EnrichedIR): string => {
  const units = ec2Units(ir);
  if (units.length === 0) return "";
  const publicPorts = units.flatMap((u) => u.ports.filter((p) => p.public));
  const ingress = [
    ...new Map(publicPorts.map((p) => [`${p.host ?? p.container}:${p.protocol}`, p])).values(),
  ]
    .map(
      (p) => `  ingress {
    from_port = ${p.host ?? p.container}
    to_port = ${p.host ?? p.container}
    protocol = ${quote(p.protocol)}
    cidr_blocks = ["0.0.0.0/0"]
  }`,
    )
    .join("\n");
  const esc = (v: string) => `'${v.replaceAll("'", "'\\''")}'`;
  const runs = units
    .map((u) => {
      const ports = u.ports.map((p) => `-p ${p.host ?? p.container}:${p.container}`).join(" ");
      const env = Object.entries(u.env)
        .filter(([k]) => !u.secrets.includes(k))
        .map(([k, v]) => `-e ${esc(`${k}=${v}`)}`)
        .join(" ");
      const secretTodo = u.secrets
        .map(
          (key) =>
            `# TODO(dodeploy): ${JSON.stringify(u.name)} secret ${JSON.stringify(key)}: value intentionally omitted; provision it on the host and pass it with -e ${key} (no value) or docker --env-file`,
        )
        .join("\n");
      const image = u.image ?? `\${var.${tfName(u.name)}_image}`;
      const name = u.name.replace(/[^a-zA-Z0-9_.-]/g, "-");
      // docker run CLI: --entrypoint takes the binary; remaining entrypoint args and the
      // command follow the image, each shell-quoted, preserving the exec-form argv order.
      const entrypoint =
        u.entrypoint !== undefined ? ` --entrypoint ${esc(u.entrypoint[0] ?? "")}` : "";
      const args = [...(u.entrypoint?.slice(1) ?? []), ...(u.command ?? [])].map(esc).join(" ");
      return `${secretTodo}${secretTodo ? "\n" : ""}docker run -d --restart unless-stopped --name ${name}${entrypoint} ${ports}${env ? ` ${env}` : ""} ${esc(image)}${args ? ` ${args}` : ""}`;
    })
    .join("\n");
  return `data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "name"
    values = ["al2023-ami-2023.*-x86_64"]
  }
}

resource "aws_security_group" "ec2_box" {
  name   = "${tfName(ir.meta.name)}-box"
  vpc_id = aws_vpc.main.id
${ingress}
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_instance" "box" {
  ami                         = data.aws_ami.al2023.id
  instance_type               = "t3.small"
  subnet_id                   = aws_subnet.public_a.id
  vpc_security_group_ids      = [aws_security_group.ec2_box.id]
  associate_public_ip_address = true
  user_data                   = <<-EOF
#!/bin/bash
dnf install -y docker
systemctl enable --now docker
${runs}
EOF
  tags = { Project = var.project_name }
}`;
};

const apprunnerSection = (ir: EnrichedIR): string => {
  const units = apprunnerUnits(ir);
  if (units.length === 0) return "";
  const partitionDataSource =
    fargateUnits(ir).length === 0 ? 'data "aws_partition" "current" {}\n\n' : "";
  const services = units
    .map((u) => {
      const label = tfName(u.name);
      const port = u.ports[0]?.container ?? 8080;
      const repoType = u.image?.startsWith("public.ecr.aws") ? "ECR_PUBLIC" : "ECR";
      const envVars = Object.entries(u.env)
        .filter(([k]) => !u.secrets.includes(k))
        .map(([k, v]) => `${k} = ${quote(v)}`)
        .join(", ");
      const secretTodo = u.secrets
        .map(
          (key) =>
            `# TODO(dodeploy): ${JSON.stringify(u.name)} secret ${JSON.stringify(key)}: value intentionally omitted; store it in Secrets Manager and wire it via runtime_environment_secrets`,
        )
        .join("\n");
      return `${secretTodo}${secretTodo ? "\n" : ""}resource "aws_apprunner_service" "${label}" {
  service_name = ${quote(`${tfName(ir.meta.name)}-${label}`)}
  source_configuration {
${
  repoType === "ECR"
    ? `    authentication_configuration {
      access_role_arn = aws_iam_role.apprunner_ecr.arn
    }\n`
    : ""
}    image_repository {
      image_identifier      = ${unitImage(u)}
      image_repository_type = ${quote(repoType)}
      image_configuration {
        port = "${port}"${envVars ? `\n        runtime_environment_variables = { ${envVars} }` : ""}${u.command !== undefined && u.command.length > 0 ? `\n        start_command = ${quote(u.command.join(" "))}` : ""}
      }
    }
  }
}`;
    })
    .join("\n\n");
  return `${partitionDataSource}resource "aws_iam_role" "apprunner_ecr" {
  name_prefix = "dodeploy-apprunner-"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Service = "build.apprunner.amazonaws.com" }
      Action = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "apprunner_ecr" {
  role       = aws_iam_role.apprunner_ecr.name
  policy_arn = "arn:\${data.aws_partition.current.partition}:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess"
}

${services}`;
};

const datastoreNetworkSection = (ir: EnrichedIR): string => {
  const groups: string[] = [];
  if (ir.datastores.some((d) => d.engine === "postgres" || d.engine === "mysql")) {
    groups.push(`resource "aws_db_subnet_group" "main" {
  name_prefix = "dodeploy-"
  subnet_ids = [aws_subnet.private_a.id, aws_subnet.private_b.id]
}`);
  }
  if (ir.datastores.some((d) => d.engine === "redis")) {
    groups.push(`resource "aws_elasticache_subnet_group" "main" {
  name = "${tfName(ir.meta.name)}-cache"
  subnet_ids = [aws_subnet.private_a.id, aws_subnet.private_b.id]
}`);
  }
  if (
    ir.datastores.some(
      (d) => d.engine !== "postgres" && d.engine !== "mysql" && d.engine !== "redis",
    )
  ) {
    groups.push(`resource "aws_docdb_subnet_group" "main" {
  name_prefix = "dodeploy-"
  subnet_ids = [aws_subnet.private_a.id, aws_subnet.private_b.id]
}`);
  }
  return groups.join("\n\n");
};

const datastoreBlock = (d: EnrichedIR["datastores"][number]): string => {
  const label = tfName(d.name);
  if (d.engine === "postgres" || d.engine === "mysql") {
    return `resource "aws_db_instance" "${label}" {
  identifier           = ${quote(label)}
  engine               = ${quote(d.engine)}
  engine_version       = ${quote(resolveDatabaseVersion("aws", d).version)}
  instance_class       = "db.t3.micro"
  allocated_storage    = 20
  username             = "dodeploy"
  password             = var.db_password
  skip_final_snapshot  = true
  db_subnet_group_name = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.service_${label}.id]
  publicly_accessible = false
}`;
  }
  if (d.engine === "redis") {
    return `resource "aws_elasticache_cluster" "${label}" {
  cluster_id      = ${quote(label)}
  engine          = "redis"
  node_type       = "cache.t3.micro"
  num_cache_nodes = 1
  subnet_group_name = aws_elasticache_subnet_group.main.name
  security_group_ids = [aws_security_group.service_${label}.id]
}`;
  }
  return `resource "aws_docdb_cluster" "${label}" {
  cluster_identifier  = ${quote(label)}
  engine              = "docdb"
  master_username     = "dodeploy"
  master_password     = var.db_password
  skip_final_snapshot = true
  db_subnet_group_name = aws_docdb_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.service_${label}.id]
}

resource "aws_docdb_cluster_instance" "${label}" {
  cluster_identifier = aws_docdb_cluster.${label}.id
  instance_class     = "db.t3.medium"
}`;
};

const storageBlock = (s: EnrichedIR["storage"][number], ir: EnrichedIR): string => {
  const label = tfName(s.name);
  if (s.kind === "shared-volume" || s.kind === "local-volume") {
    return `# TODO(dodeploy): volume ${JSON.stringify(s.name)} deferred: IR lacks container mount paths. Define EFS mount targets, task volumes and container mountPoints manually before applying.`;
  }
  return `resource "aws_s3_bucket" "${label}" {
  bucket = "${tfName(ir.meta.name)}-${label}"
  tags   = { Project = var.project_name }
}

resource "aws_s3_bucket_public_access_block" "${label}" {
  bucket = aws_s3_bucket.${label}.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}`;
};

const outputsTf = (ir: EnrichedIR): string => {
  const lines: string[] = [];
  if (publicRoutes(ir).length > 0) {
    lines.push(`output "alb_dns_name" {
  value = aws_lb.main.dns_name
}`);
  }
  if (ec2Units(ir).length > 0) {
    lines.push(`output "box_public_ip" {
  value = aws_instance.box.public_ip
}`);
  }
  for (const u of apprunnerUnits(ir)) {
    const label = tfName(u.name);
    lines.push(`output "apprunner_${label}_url" {
  value = aws_apprunner_service.${label}.service_url
}`);
  }
  for (const d of ir.datastores) {
    const label = tfName(d.name);
    if (d.engine === "postgres" || d.engine === "mysql") {
      lines.push(`output "db_${label}_address" {
  value = aws_db_instance.${label}.address
}`);
    } else if (d.engine === "redis") {
      lines.push(`output "cache_${label}_address" {
  value = aws_elasticache_cluster.${label}.cache_nodes[0].address
}`);
    } else {
      lines.push(`output "db_${label}_endpoint" {
  value = aws_docdb_cluster.${label}.endpoint
}`);
    }
  }
  for (const s of ir.storage) {
    if (s.kind === "static-assets" || s.kind === "uploads") {
      lines.push(`output "bucket_${tfName(s.name)}" {
  value = aws_s3_bucket.${tfName(s.name)}.bucket
}`);
    }
  }
  return `${HEADER}${lines.join("\n\n")}`;
};

export function renderAws(ir: EnrichedIR): RenderResult {
  const diagnostics: RenderResult["diagnostics"] = [];
  const dupError = duplicateLabelError(ir.compute.map((u) => u.name));
  if (dupError !== undefined) {
    diagnostics.push({ stage: "render", severity: "error", message: dupError });
  }

  for (const datastore of ir.datastores) {
    if (datastore.engine === "postgres" || datastore.engine === "mysql") {
      diagnostics.push(...resolveDatabaseVersion("aws", datastore).diagnostics);
    }
  }
  const routes = publicRoutes(ir);
  const routeTodos: string[] = [];
  for (const unit of fargateUnits(ir)) {
    for (const port of unit.ports.filter((p) => p.public)) {
      if (routes.some((r) => r.unit === unit && r.port === port)) continue;
      const reason =
        port.protocol === "udp"
          ? "UDP/non-HTTP routing requires a manually configured NLB"
          : "ambiguous or unsupported public route (unique Compose host ports and at most five HTTP target groups per service required)";
      const message = `${quote(unit.name)}:${port.container}: ${reason}`;
      diagnostics.push({ stage: "render", severity: "warning", message });
      routeTodos.push(
        `# TODO(dodeploy): ${JSON.stringify(unit.name)}:${port.container}: ${reason}`,
      );
    }
  }
  for (const unit of fargateUnits(ir)) {
    const { adjustments } = fargateSize(unit);
    if (adjustments.length > 0) {
      diagnostics.push({
        stage: "render",
        severity: "warning",
        message: `${quote(unit.name)}: requested task size is not a supported Fargate combination — snapped ${adjustments.join(", ")}`,
      });
    }
  }
  for (const unit of apprunnerUnits(ir)) {
    if (unit.entrypoint !== undefined && unit.entrypoint.length > 0) {
      diagnostics.push({
        stage: "render",
        severity: "warning",
        message: `${quote(unit.name)}: entrypoint is not supported by App Runner and was dropped; bake it into the image or use command (rendered as start_command) instead`,
      });
    }
  }
  for (const unit of ir.compute) {
    for (const key of unit.secrets) {
      diagnostics.push({
        stage: "render",
        severity: "warning",
        message: `${quote(unit.name)}: secret ${quote(key)} requires manual Secrets Manager injection and ${
          unit.target === "ec2"
            ? "manual provisioning on the EC2 box"
            : unit.target === "apprunner"
              ? "App Runner secrets configuration"
              : "ECS execution role permissions"
        }`,
      });
    }
  }
  for (const storage of ir.storage.filter(
    (s) => s.kind === "shared-volume" || s.kind === "local-volume",
  )) {
    diagnostics.push({
      stage: "render",
      severity: "warning",
      message: `volume ${quote(storage.name)} deferred: IR lacks container mount paths; configure persistent mounts manually`,
    });
  }
  if (ec2Units(ir).length > 0) {
    diagnostics.push({
      stage: "render",
      severity: "info",
      message: "ec2 box is a single point of failure (no HA) — cheapest option",
    });
    if (fargateUnits(ir).length === 0) {
      diagnostics.push({
        stage: "render",
        severity: "info",
        message:
          "private subnets + NAT gateway (~$$/mo) are unused by EC2-only computes — remove network pieces manually if unneeded",
      });
    }
  }

  const network = renderSections(
    [
      { name: "vpc", builder: vpcSection },
      { name: "routing", builder: routingSection },
      { name: "alb", builder: albSection },
      { name: "security-groups", builder: sgSection },
      { name: "service-discovery", builder: discoverySection },
    ],
    ir,
  );
  const compute =
    dupError !== undefined
      ? { content: "", diagnostics: [] }
      : renderSections(
          [
            { name: "ecs-cluster", builder: ecsClusterSection },
            { name: "task-definitions", builder: taskDefSection },
            { name: "ecs-services", builder: ecsServiceSection },
            { name: "stateful", builder: statefulSection },
          ],
          ir,
        );
  const data = renderSections(
    [
      { name: "datastore-network", builder: datastoreNetworkSection },
      ...ir.datastores.map((d) => ({
        name: `datastore-${d.name}`,
        builder: () => datastoreBlock(d),
      })),
      ...ir.storage.map((s) => ({ name: `storage-${s.name}`, builder: () => storageBlock(s, ir) })),
    ],
    ir,
  );

  diagnostics.push(...network.diagnostics, ...compute.diagnostics, ...data.diagnostics);

  const files: Record<string, string> = {
    "providers.tf": providersTf(),
    "variables.tf": variablesTf(ir),
    "network.tf": `${HEADER}${routeTodos.join("\n")}\n${network.content}`,
    "compute.tf": `${HEADER}${dupError !== undefined ? `# TODO(dodeploy): ${dupError}\n` : compute.content}`,
    "data.tf": `${HEADER}${data.content}`,
    "outputs.tf": outputsTf(ir),
  };
  if (ec2Units(ir).length > 0) {
    files["ec2.tf"] = `${HEADER}${ec2BoxSection(ir)}`;
  }
  if (apprunnerUnits(ir).length > 0) {
    files["apprunner.tf"] = `${HEADER}${apprunnerSection(ir)}`;
  }

  return {
    files: alignFiles(files),
    diagnostics,
  };
}
