import type { EnrichedIR } from "../../ir/index.js";
import { renderSections } from "../../render/engine.js";
import { duplicateLabelError, quote, tfName } from "../../render/hcl.js";
import type { RenderResult } from "../../render/types.js";

import { resolveDatabaseVersion } from "../database-version.js";

const HEADER = "# Generated by DoDeploy — review before applying.\n";

const providersTf = (): string =>
  `${HEADER}
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

provider "azurerm" {
  features {}
}
`;

const variablesTf = (ir: EnrichedIR): string => {
  const builderVars = ir.compute
    .filter((u) => u.buildContext !== undefined && u.image === undefined)
    .map(
      (u) => `variable "${tfName(u.name)}_image" {
  type        = string
  description = "Full image URI for ${u.name} (build from ${u.buildContext ?? "context"} and push to ACR)"
}
`,
    )
    .join("\n");
  return `${HEADER}
variable "project_name" {
  type = string
}

variable "region" {
  type = string
}

variable "vpc_cidr" {
  type    = string
  default = "10.0.0.0/16"
}

variable "db_password" {
  type        = string
  sensitive   = true
  description = "Administrator password for managed databases — set via TF_VAR_db_password or a secrets backend"
}

${builderVars}`;
};

const networkSection = (): string => `resource "azurerm_resource_group" "main" {
  name     = var.project_name
  location = var.region
}

resource "azurerm_virtual_network" "main" {
  name                = "\${var.project_name}-vnet"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  address_space       = [var.vpc_cidr]
}

resource "azurerm_subnet" "main" {
  name                 = "\${var.project_name}-subnet"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_container_app_environment" "main" {
  name                = "\${var.project_name}-env"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
}`;

const computeSection = (ir: EnrichedIR): string =>
  ir.compute
    .filter((u) => u.kind !== "stateful")
    .map((u) => {
      const label = tfName(u.name);
      // Container Apps ingress is TCP-only; UDP public ports are reported in renderAzure.
      const publicPort = u.ports.find((p) => p.public && p.protocol === "tcp");
      const image =
        u.image !== undefined
          ? quote(u.image)
          : `var.${label}_image # TODO(dodeploy): build & push this image (see ACR recommendation)`;
      const envVars = Object.entries(u.env)
        .filter(([key]) => !u.secrets.includes(key))
        .map(
          ([key, value]) =>
            `      env {\n        name  = ${quote(key)}\n        value = ${quote(value)}\n      }`,
        )
        .join("\n");
      const secretTodos = [...new Set(u.secrets)]
        .map(
          (key) =>
            `# TODO(dodeploy): service ${JSON.stringify(u.name)} secret ${JSON.stringify(key)}: configure Container Apps secret (or Key Vault reference) and container env.secret_name manually.`,
        )
        .join("\n");
      const env = envVars.length > 0 ? `\n${envVars}` : "";
      // Container Apps: entrypoint → command, command → args.
      const commandArgs =
        (u.entrypoint !== undefined
          ? `\n        command = [${u.entrypoint.map(quote).join(", ")}]`
          : "") +
        (u.command !== undefined ? `\n        args    = [${u.command.map(quote).join(", ")}]` : "");
      const ingress =
        u.kind === "web" && publicPort !== undefined
          ? `
  ingress {
    external_enabled = true
    target_port      = ${publicPort.container}

    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }`
          : "";
      // Apps without ingress need a positive minimum or they scale to zero with
      // no restart trigger (https://learn.microsoft.com/en-us/azure/container-apps/scale-app).
      const minReplicas =
        u.kind === "web" && publicPort !== undefined ? "" : "\n    min_replicas = 1";
      return `${secretTodos.length > 0 ? `${secretTodos}\n` : ""}resource "azurerm_container_app" "${label}" {
  name                         = ${quote(label)}
  resource_group_name          = azurerm_resource_group.main.name
  container_app_environment_id = azurerm_container_app_environment.main.id
  revision_mode                = "Single"

  template {${minReplicas}
    container {
      name   = ${quote(label)}
      image  = ${image}
      cpu    = ${u.cpu ?? 0.5}
      memory = "${u.memoryMb ?? 1024}Mi"${commandArgs}${env}
    }
  }
${ingress}
}`;
    })
    .join("\n\n");

const statefulSection = (ir: EnrichedIR): string => {
  const stateful = ir.compute.filter((u) => u.kind === "stateful");
  if (stateful.length === 0) return "";
  throw new Error(
    `stateful service(s) ${stateful.map((u) => `"${u.name}"`).join(", ")}: VM/VMSS rendering is not yet supported by this renderer`,
  );
};

const datastoreBlock = (d: EnrichedIR["datastores"][number]): string => {
  const label = tfName(d.name);
  if (d.engine === "postgres" || d.engine === "mysql") {
    return `# TODO(dodeploy): datastore ${JSON.stringify(d.name)}: configure database firewall rules or delegated subnet/private DNS and Container Apps VNet integration before connecting services.
resource "${d.engine === "mysql" ? "azurerm_mysql_flexible_server" : "azurerm_postgresql_flexible_server"}" "${label}" {
  name                   = "\${var.project_name}-${label}"
  resource_group_name    = azurerm_resource_group.main.name
  location               = azurerm_resource_group.main.location
  administrator_login    = "dodeploy"
  administrator_password = var.db_password
  sku_name               = "B_Standard_B1ms"
  version                = "${resolveDatabaseVersion("azure", d).version}"
  zone                   = "1"
}`;
  }
  if (d.engine === "redis") {
    return `resource "azurerm_redis_cache" "${label}" {
  name                 = "\${var.project_name}-${label}"
  location             = azurerm_resource_group.main.location
  resource_group_name  = azurerm_resource_group.main.name
  capacity             = 1
  family               = "C"
  sku_name             = "Basic"
  non_ssl_port_enabled = false
}`;
  }
  throw new Error(
    `datastore "${d.name}": Cosmos DB (Mongo API) rendering deferred (costly abstraction) — add a TODO issue if you need it`,
  );
};

const storageAccountSection = (ir: EnrichedIR): string => {
  if (!ir.storage.some((s) => s.kind === "static-assets" || s.kind === "uploads")) return "";
  return `resource "azurerm_storage_account" "main" {
  name                     = replace("\${var.project_name}storage", "-", "")
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}`;
};

const storageBlock = (s: EnrichedIR["storage"][number]): string => {
  const label = tfName(s.name);
  if (s.kind === "shared-volume" || s.kind === "local-volume") {
    throw new Error(
      `volume ${quote(s.name)}: Azure Files attachment deferred because IR lacks container mount paths; configure environment storage, volume and container volume_mounts manually`,
    );
  }
  return `resource "azurerm_storage_container" "${label}" {
  name                  = ${quote(label)}
  storage_account_name  = azurerm_storage_account.main.name
  container_access_type = "private"
}`;
};

const outputsTf = (ir: EnrichedIR): string => {
  const lines: string[] = [];
  for (const u of ir.compute.filter((c) => c.kind === "web" && c.ports.some((p) => p.public))) {
    lines.push(`output "service_${tfName(u.name)}_fqdn" {
  value = azurerm_container_app.${tfName(u.name)}.ingress[0].fqdn
}`);
  }
  for (const d of ir.datastores) {
    if (d.engine === "postgres" || d.engine === "mysql") {
      lines.push(`output "db_${tfName(d.name)}_fqdn" {
  value = ${d.engine === "mysql" ? "azurerm_mysql_flexible_server" : "azurerm_postgresql_flexible_server"}.${tfName(d.name)}.fqdn
}`);
    } else if (d.engine === "redis") {
      lines.push(`output "cache_${tfName(d.name)}_hostname" {
  value = azurerm_redis_cache.${tfName(d.name)}.hostname
}`);
    }
  }
  return `${HEADER}${lines.join("\n\n")}`;
};

export function renderAzure(ir: EnrichedIR): RenderResult {
  const diagnostics: RenderResult["diagnostics"] = [];
  for (const d of ir.datastores.filter((d) => d.engine === "postgres" || d.engine === "mysql")) {
    diagnostics.push(...resolveDatabaseVersion("azure", d).diagnostics);
    diagnostics.push({
      stage: "render",
      severity: "warning",
      message: `datastore ${quote(d.name)}: Container Apps database connectivity requires manual firewall rules or delegated subnet/private DNS and Container Apps VNet integration`,
    });
  }
  for (const u of ir.compute) {
    for (const key of new Set(u.secrets)) {
      diagnostics.push({
        stage: "render",
        severity: "warning",
        message: `service ${quote(u.name)} secret ${quote(key)} requires manual Container Apps secret injection`,
      });
    }
  }

  const dupError = duplicateLabelError(ir.compute.map((u) => u.name));
  if (dupError !== undefined) {
    diagnostics.push({ stage: "render", severity: "error", message: dupError });
  }

  // Every public port that won't be exposed must be visible to the user.
  for (const unit of ir.compute.filter((u) => u.kind !== "stateful")) {
    const publicPorts = unit.ports.filter((p) => p.public);
    const served = unit.kind === "web" ? publicPorts.find((p) => p.protocol === "tcp") : undefined;
    for (const port of publicPorts) {
      if (port === served) continue;
      const reason =
        port.protocol === "udp"
          ? "UDP is not supported by Container Apps ingress"
          : unit.kind !== "web"
            ? "apps without ingress expose no ports"
            : "Container Apps ingress supports a single target port";
      diagnostics.push({
        stage: "render",
        severity: "warning",
        message: `${quote(unit.name)}:${port.container}/${port.protocol} not exposed: ${reason}; route this port separately`,
      });
    }
  }

  const network = renderSections([{ name: "network", builder: networkSection }], ir);
  const compute =
    dupError !== undefined
      ? { content: "", diagnostics: [] }
      : renderSections(
          [
            { name: "container-apps", builder: computeSection },
            { name: "stateful", builder: statefulSection },
          ],
          ir,
        );
  const data = renderSections(
    [
      ...ir.datastores.map((d) => ({
        name: `datastore-${d.name}`,
        builder: () => datastoreBlock(d),
      })),
      { name: "storage-account", builder: storageAccountSection },
      ...ir.storage.map((s) => ({ name: `storage-${s.name}`, builder: () => storageBlock(s) })),
    ],
    ir,
  );
  diagnostics.push(...network.diagnostics, ...compute.diagnostics, ...data.diagnostics);

  return {
    files: {
      "providers.tf": providersTf(),
      "variables.tf": variablesTf(ir),
      "network.tf": `${HEADER}${network.content}`,
      "compute.tf": `${HEADER}${dupError !== undefined ? `# TODO(dodeploy): ${dupError}\n` : compute.content}`,
      "data.tf": `${HEADER}${data.content}`,
      "outputs.tf": outputsTf(ir),
    },
    diagnostics,
  };
}
