import type { EnrichedIR } from "../../ir/index.js";
import { renderSections } from "../../render/engine.js";
import { quote, tfName } from "../../render/hcl.js";
import type { RenderResult } from "../../render/types.js";

const HEADER = "# Generated by DoDeploy — review before applying.\n";

const providersTf = (): string =>
  `${HEADER}
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

provider "azurerm" {
  features {}
}
`;

const variablesTf = (ir: EnrichedIR): string => {
  const builderVars = ir.compute
    .filter((u) => u.buildContext !== undefined && u.image === undefined)
    .map(
      (u) => `variable "${tfName(u.name)}_image" {
  type        = string
  description = "Full image URI for ${u.name} (build from ${u.buildContext ?? "context"} and push to ACR)"
}
`,
    )
    .join("\n");
  return `${HEADER}
variable "project_name" {
  type = string
}

variable "region" {
  type = string
}

variable "vpc_cidr" {
  type    = string
  default = "10.0.0.0/16"
}

variable "db_password" {
  type        = string
  sensitive   = true
  description = "Administrator password for managed databases — set via TF_VAR_db_password or a secrets backend"
}

${builderVars}`;
};

const networkSection = (): string => `resource "azurerm_resource_group" "main" {
  name     = var.project_name
  location = var.region
}

resource "azurerm_virtual_network" "main" {
  name                = "\${var.project_name}-vnet"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  address_space       = [var.vpc_cidr]
}

resource "azurerm_subnet" "main" {
  name                 = "\${var.project_name}-subnet"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_container_app_environment" "main" {
  name                = "\${var.project_name}-env"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
}`;

const computeSection = (ir: EnrichedIR): string =>
  ir.compute
    .filter((u) => u.kind !== "stateful")
    .map((u) => {
      const label = tfName(u.name);
      const publicPort = u.ports.find((p) => p.public);
      const image =
        u.image !== undefined
          ? quote(u.image)
          : `var.${label}_image # TODO(dodeploy): build & push this image (see ACR recommendation)`;
      const envVars = Object.entries(u.env)
        .filter(([key]) => !u.secrets.includes(key))
        .map(([key, value]) => `        { name = ${quote(key)}, value = ${quote(value)} },`)
        .join("\n");
      const env =
        envVars.length > 0
          ? `
      env = [
${envVars}
      ]`
          : "";
      const ingress =
        u.kind === "web" && publicPort !== undefined
          ? `
  ingress {
    external_enabled = true
    target_port      = ${publicPort.container}

    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }`
          : "";
      return `resource "azurerm_container_app" "${label}" {
  name                         = ${quote(label)}
  resource_group_name          = azurerm_resource_group.main.name
  container_app_environment_id = azurerm_container_app_environment.main.id
  revision_mode                = "Single"

  template {
    container {
      name   = ${quote(label)}
      image  = ${image}
      cpu    = ${u.cpu ?? 0.5}
      memory = "${u.memoryMb ?? 1024}Mi"${env}
    }
  }
${ingress}
}`;
    })
    .join("\n\n");

const statefulSection = (ir: EnrichedIR): string => {
  const stateful = ir.compute.filter((u) => u.kind === "stateful");
  if (stateful.length === 0) return "";
  throw new Error(
    `stateful service(s) ${stateful.map((u) => `"${u.name}"`).join(", ")}: VM/VMSS rendering is not yet supported by this renderer`,
  );
};

const datastoreBlock = (d: EnrichedIR["datastores"][number]): string => {
  const label = tfName(d.name);
  if (d.engine === "postgres" || d.engine === "mysql") {
    return `resource "azurerm_postgresql_flexible_server" "${label}" {
  name                   = "\${var.project_name}-${label}"
  resource_group_name    = azurerm_resource_group.main.name
  location               = azurerm_resource_group.main.location
  administrator_login    = "dodeploy"
  administrator_password = var.db_password
  sku_name               = "B_Standard_B1ms"
  version                = "${d.version ?? "16"}"
  zone                   = "1"
}`;
  }
  if (d.engine === "redis") {
    return `resource "azurerm_redis_cache" "${label}" {
  name                 = "\${var.project_name}-${label}"
  location             = azurerm_resource_group.main.location
  resource_group_name  = azurerm_resource_group.main.name
  capacity             = 1
  family               = "C"
  sku_name             = "Basic"
  non_ssl_port_enabled = false
}`;
  }
  throw new Error(
    `datastore "${d.name}": Cosmos DB (Mongo API) rendering deferred (costly abstraction) — add a TODO issue if you need it`,
  );
};

const storageAccountSection = (ir: EnrichedIR): string => {
  if (ir.storage.length === 0) return "";
  return `resource "azurerm_storage_account" "main" {
  name                     = replace("\${var.project_name}storage", "-", "")
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}`;
};

const storageBlock = (s: EnrichedIR["storage"][number]): string => {
  const label = tfName(s.name);
  if (s.kind === "shared-volume" || s.kind === "local-volume") {
    return `resource "azurerm_storage_share" "${label}" {
  name                 = ${quote(label)}
  storage_account_name = azurerm_storage_account.main.name
  quota                = 100
}`;
  }
  return `resource "azurerm_storage_container" "${label}" {
  name                  = ${quote(label)}
  storage_account_name  = azurerm_storage_account.main.name
  container_access_type = "private"
}`;
};

const outputsTf = (ir: EnrichedIR): string => {
  const lines: string[] = [];
  for (const u of ir.compute.filter((c) => c.kind === "web" && c.ports.some((p) => p.public))) {
    lines.push(`output "service_${tfName(u.name)}_fqdn" {
  value = azurerm_container_app.${tfName(u.name)}.ingress[0].fqdn
}`);
  }
  for (const d of ir.datastores) {
    if (d.engine === "postgres" || d.engine === "mysql") {
      lines.push(`output "db_${tfName(d.name)}_fqdn" {
  value = azurerm_postgresql_flexible_server.${tfName(d.name)}.fqdn
}`);
    } else if (d.engine === "redis") {
      lines.push(`output "cache_${tfName(d.name)}_hostname" {
  value = azurerm_redis_cache.${tfName(d.name)}.hostname
}`);
    }
  }
  return `${HEADER}${lines.join("\n\n")}`;
};

export function renderAzure(ir: EnrichedIR): RenderResult {
  const diagnostics: RenderResult["diagnostics"] = [];

  const network = renderSections([{ name: "network", builder: networkSection }], ir);
  const compute = renderSections(
    [
      { name: "container-apps", builder: computeSection },
      { name: "stateful", builder: statefulSection },
    ],
    ir,
  );
  const data = renderSections(
    [
      ...ir.datastores.map((d) => ({
        name: `datastore-${d.name}`,
        builder: () => datastoreBlock(d),
      })),
      { name: "storage-account", builder: storageAccountSection },
      ...ir.storage.map((s) => ({ name: `storage-${s.name}`, builder: () => storageBlock(s) })),
    ],
    ir,
  );
  diagnostics.push(...network.diagnostics, ...compute.diagnostics, ...data.diagnostics);

  return {
    files: {
      "providers.tf": providersTf(),
      "variables.tf": variablesTf(ir),
      "network.tf": `${HEADER}${network.content}`,
      "compute.tf": `${HEADER}${compute.content}`,
      "data.tf": `${HEADER}${data.content}`,
      "outputs.tf": outputsTf(ir),
    },
    diagnostics,
  };
}
