import type { EnrichedIR } from "../../ir/index.js";
import { renderSections } from "../../render/engine.js";
import { quote, tfName } from "../../render/hcl.js";
import type { RenderResult } from "../../render/types.js";

const HEADER = "# Generated by DoDeploy — review before applying.\n";

const providersTf = (): string =>
  `${HEADER}
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }
}

provider "google" {
  region = var.region
}
`;

const variablesTf = (ir: EnrichedIR): string => {
  const builderVars = ir.compute
    .filter((u) => u.buildContext !== undefined && u.image === undefined)
    .map(
      (u) => `variable "${tfName(u.name)}_image" {
  type        = string
  description = "Full image URI for ${u.name} (build from ${u.buildContext ?? "context"} and push to Artifact Registry)"
}
`,
    )
    .join("\n");
  return `${HEADER}
variable "project_name" {
  type = string
}

variable "region" {
  type = string
}

variable "vpc_cidr" {
  type    = string
  default = "10.0.0.0/16"
}

variable "db_password" {
  type        = string
  sensitive   = true
  description = "Root password for managed databases — set via TF_VAR_db_password or a secrets backend"
}

${builderVars}`;
};

const networkSection = (): string => `resource "google_compute_network" "main" {
  name                    = var.project_name
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "main" {
  name          = "\${var.project_name}-subnet"
  ip_cidr_range = var.vpc_cidr
  region        = var.region
  network       = google_compute_network.main.id
}`;

const computeSection = (ir: EnrichedIR): string =>
  ir.compute
    .filter((u) => u.kind !== "stateful")
    .map((u) => {
      const label = tfName(u.name);
      const publicPort = u.ports.find((p) => p.public);
      const image =
        u.image !== undefined
          ? quote(u.image)
          : `var.${label}_image # TODO(dodeploy): build & push this image (see Artifact Registry recommendation)`;
      const ports =
        publicPort !== undefined
          ? `
    ports {
      container_port = ${publicPort.container}
    }`
          : "";
      const ingress = u.kind === "web" ? "INGRESS_TRAFFIC_ALL" : "INGRESS_TRAFFIC_INTERNAL_ONLY";
      const envVars = Object.entries(u.env)
        .filter(([key]) => !u.secrets.includes(key))
        .map(([key, value]) => `        { name = ${quote(key)}, value = ${quote(value)} },`)
        .join("\n");
      const env =
        envVars.length > 0
          ? `
      env = [
${envVars}
      ]`
          : "";
      return `resource "google_cloud_run_v2_service" "${label}" {
  name     = ${quote(label)}
  location = var.region
  ingress  = "${ingress}"

  template {
    containers {
      image = ${image}${ports}${env}
    }

    scaling {
      max_instance_count = 3
    }
  }
}`;
    })
    .join("\n\n");

const statefulSection = (ir: EnrichedIR): string => {
  const stateful = ir.compute.filter((u) => u.kind === "stateful");
  if (stateful.length === 0) return "";
  throw new Error(
    `stateful service(s) ${stateful.map((u) => `"${u.name}"`).join(", ")}: GCE/VM rendering is not yet supported by this renderer`,
  );
};

const DATASTORE_VERSIONS: Record<string, (v: string | undefined) => string> = {
  postgres: (v) => `POSTGRES_${v ?? "16"}`,
  mysql: () => "MYSQL_8_0",
};

const datastoreBlock = (d: EnrichedIR["datastores"][number]): string => {
  const label = tfName(d.name);
  if (d.engine === "postgres" || d.engine === "mysql") {
    return `resource "google_sql_database_instance" "${label}" {
  name             = ${quote(label)}
  region           = var.region
  database_version = "${DATASTORE_VERSIONS[d.engine]?.(d.version) ?? "POSTGRES_16"}"

  settings {
    tier = "db-f1-micro"
  }

  root_password = var.db_password
}`;
  }
  if (d.engine === "redis") {
    return `resource "google_redis_instance" "${label}" {
  name               = ${quote(label)}
  region             = var.region
  memory_size_gb     = 1
  authorized_network = google_compute_network.main.id
}`;
  }
  throw new Error(
    `datastore "${d.name}": no native managed MongoDB on GCP — Atlas or self-managed GCE is not rendered yet`,
  );
};

const storageBlock = (s: EnrichedIR["storage"][number], ir: EnrichedIR): string => {
  const label = tfName(s.name);
  if (s.kind === "shared-volume" || s.kind === "local-volume") {
    throw new Error(
      `volume "${s.name}": Filestore rendering deferred (costly abstraction) — mount S3/GCS or add a TODO issue`,
    );
  }
  return `resource "google_storage_bucket" "${label}" {
  name          = "${tfName(ir.meta.name)}-${label}"
  location      = var.region
  force_destroy = false

  uniform_bucket_level_access = true
}`;
};

const outputsTf = (ir: EnrichedIR): string => {
  const lines: string[] = [];
  for (const u of ir.compute.filter((c) => c.kind !== "stateful")) {
    lines.push(`output "service_${tfName(u.name)}_url" {
  value = google_cloud_run_v2_service.${tfName(u.name)}.uri
}`);
  }
  for (const d of ir.datastores) {
    if (d.engine === "postgres" || d.engine === "mysql") {
      lines.push(`output "db_${tfName(d.name)}_ip" {
  value = google_sql_database_instance.${tfName(d.name)}.private_ip_address
}`);
    } else if (d.engine === "redis") {
      lines.push(`output "cache_${tfName(d.name)}_host" {
  value = google_redis_instance.${tfName(d.name)}.host
}`);
    }
  }
  for (const s of ir.storage) {
    if (s.kind === "static-assets" || s.kind === "uploads") {
      lines.push(`output "bucket_${tfName(s.name)}" {
  value = google_storage_bucket.${tfName(s.name)}.name
}`);
    }
  }
  return `${HEADER}${lines.join("\n\n")}`;
};

export function renderGcp(ir: EnrichedIR): RenderResult {
  const diagnostics: RenderResult["diagnostics"] = [];

  const network = renderSections([{ name: "network", builder: networkSection }], ir);
  const compute = renderSections(
    [
      { name: "cloud-run", builder: computeSection },
      { name: "stateful", builder: statefulSection },
    ],
    ir,
  );
  const data = renderSections(
    [
      ...ir.datastores.map((d) => ({
        name: `datastore-${d.name}`,
        builder: () => datastoreBlock(d),
      })),
      ...ir.storage.map((s) => ({ name: `storage-${s.name}`, builder: () => storageBlock(s, ir) })),
    ],
    ir,
  );
  diagnostics.push(...network.diagnostics, ...compute.diagnostics, ...data.diagnostics);

  return {
    files: {
      "providers.tf": providersTf(),
      "variables.tf": variablesTf(ir),
      "network.tf": `${HEADER}${network.content}`,
      "compute.tf": `${HEADER}${compute.content}`,
      "data.tf": `${HEADER}${data.content}`,
      "outputs.tf": outputsTf(ir),
    },
    diagnostics,
  };
}
