import type { EnrichedIR } from "../../ir/index.js";
import { renderSections } from "../../render/engine.js";
import { duplicateLabelError, quote, tfName } from "../../render/hcl.js";
import type { RenderResult } from "../../render/types.js";

import { resolveDatabaseVersion } from "../database-version.js";

const HEADER = "# Generated by DoDeploy — review before applying.\n";

const providersTf = (): string =>
  `${HEADER}
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }
}

provider "google" {
  region = var.region
}
`;

const variablesTf = (ir: EnrichedIR): string => {
  const builderVars = ir.compute
    .filter((u) => u.buildContext !== undefined && u.image === undefined)
    .map(
      (u) => `variable "${tfName(u.name)}_image" {
  type        = string
  description = "Full image URI for ${u.name} (build from ${u.buildContext ?? "context"} and push to Artifact Registry)"
}
`,
    )
    .join("\n");
  return `${HEADER}
variable "project_name" {
  type = string
}

variable "region" {
  type = string
}

variable "vpc_cidr" {
  type    = string
  default = "10.0.0.0/16"
}

variable "db_password" {
  type        = string
  sensitive   = true
  description = "Root password for managed databases — set via TF_VAR_db_password or a secrets backend"
}

${builderVars}`;
};

const networkSection = (ir: EnrichedIR): string => {
  const sql = ir.datastores.some((d) => d.engine === "postgres" || d.engine === "mysql");
  const apis = [
    "compute.googleapis.com",
    ...(ir.compute.some((u) => u.kind !== "stateful") ? ["run.googleapis.com"] : []),
    ...(sql ? ["sqladmin.googleapis.com", "servicenetworking.googleapis.com"] : []),
    ...(ir.datastores.some((d) => d.engine === "redis") ? ["redis.googleapis.com"] : []),
  ];
  return `resource "google_project_service" "apis" {
  for_each           = toset([${apis.map(quote).join(", ")}])
  service            = each.value
  disable_on_destroy = false
}

resource "google_compute_network" "main" {
  name                    = var.project_name
  auto_create_subnetworks = false

  depends_on = [google_project_service.apis["compute.googleapis.com"]]
}

resource "google_compute_subnetwork" "main" {
  name          = "\${var.project_name}-subnet"
  ip_cidr_range = var.vpc_cidr
  region        = var.region
  network       = google_compute_network.main.id
}${
    sql
      ? `

resource "google_compute_global_address" "private_services" {
  name          = "\${var.project_name}-private-services"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = google_compute_network.main.id
}

resource "google_service_networking_connection" "private_services" {
  network                 = google_compute_network.main.id
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.private_services.name]

  depends_on = [google_project_service.apis["servicenetworking.googleapis.com"], google_project_service.apis["sqladmin.googleapis.com"]]
}`
      : ""
  }`;
};

const computeSection = (ir: EnrichedIR): string =>
  ir.compute
    .filter((u) => u.kind !== "stateful")
    .map((u) => {
      const label = tfName(u.name);
      // Cloud Run ingress is TCP-only; UDP public ports are reported in renderGcp.
      const publicPort = u.ports.find((p) => p.public && p.protocol === "tcp");
      const image =
        u.image !== undefined
          ? quote(u.image)
          : `var.${label}_image # TODO(dodeploy): build & push this image (see Artifact Registry recommendation)`;
      const ports =
        publicPort !== undefined
          ? `
    ports {
      container_port = ${publicPort.container}
    }`
          : "";
      const ingress = u.kind === "web" ? "INGRESS_TRAFFIC_ALL" : "INGRESS_TRAFFIC_INTERNAL_ONLY";
      const envVars = Object.entries(u.env)
        .filter(([key]) => !u.secrets.includes(key))
        .map(
          ([key, value]) =>
            `    env {\n      name  = ${quote(key)}\n      value = ${quote(value)}\n    }`,
        )
        .join("\n");
      const secretTodos = [...new Set(u.secrets)]
        .map(
          (key) =>
            `# TODO(dodeploy): service ${JSON.stringify(u.name)} secret ${JSON.stringify(key)}: configure Secret Manager and Cloud Run env.value_source.secret_key_ref; grant runtime service account secretAccessor.`,
        )
        .join("\n");
      const env = envVars.length > 0 ? `\n${envVars}` : "";
      // Cloud Run containers: entrypoint → command, command → args.
      const commandArgs =
        (u.entrypoint !== undefined
          ? `\n        command = [${u.entrypoint.map(quote).join(", ")}]`
          : "") +
        (u.command !== undefined ? `\n        args    = [${u.command.map(quote).join(", ")}]` : "");
      // Background workloads without HTTP ingress map to Cloud Run jobs, matching the
      // worker rule — services require an ingress listener and startup readiness.
      if (u.kind === "worker" || u.kind === "cron") {
        return `${secretTodos.length > 0 ? `${secretTodos}\n` : ""}resource "google_cloud_run_v2_job" "${label}" {
  name     = ${quote(label)}
  location = var.region

  template {
    template {
      containers {
        image = ${image}${commandArgs}${env}
      }
    }
  }

  depends_on = [google_project_service.apis["run.googleapis.com"]]
}`;
      }
      return `${secretTodos.length > 0 ? `${secretTodos}\n` : ""}resource "google_cloud_run_v2_service" "${label}" {
  name     = ${quote(label)}
  location = var.region
  ingress  = "${ingress}"

  template {
    containers {
      image = ${image}${commandArgs}${ports}${env}
    }

    vpc_access {
      egress = "PRIVATE_RANGES_ONLY"
      network_interfaces {
        network    = google_compute_network.main.name
        subnetwork = google_compute_subnetwork.main.name
      }
    }

    scaling {
      max_instance_count = 3
    }
  }

  depends_on = [google_project_service.apis["run.googleapis.com"]]
}`;
    })
    .join("\n\n");

const statefulSection = (ir: EnrichedIR): string => {
  const stateful = ir.compute.filter((u) => u.kind === "stateful");
  if (stateful.length === 0) return "";
  throw new Error(
    `stateful service(s) ${stateful.map((u) => `"${u.name}"`).join(", ")}: GCE/VM rendering is not yet supported by this renderer`,
  );
};

const datastoreBlock = (d: EnrichedIR["datastores"][number]): string => {
  const label = tfName(d.name);
  if (d.engine === "postgres" || d.engine === "mysql") {
    return `resource "google_sql_database_instance" "${label}" {
  name             = ${quote(label)}
  region           = var.region
  database_version = "${resolveDatabaseVersion("gcp", d).version}"

  settings {
    tier    = "db-f1-micro"
    edition = "ENTERPRISE"

    ip_configuration {
      ipv4_enabled    = false
      private_network = google_compute_network.main.id
    }
  }

  depends_on = [google_service_networking_connection.private_services]

  root_password = var.db_password
}`;
  }
  if (d.engine === "redis") {
    return `resource "google_redis_instance" "${label}" {
  name               = ${quote(label)}
  region             = var.region
  memory_size_gb     = 1
  authorized_network = google_compute_network.main.id

  depends_on = [google_project_service.apis["redis.googleapis.com"]]
}`;
  }
  throw new Error(
    `datastore "${d.name}": no native managed MongoDB on GCP — Atlas or self-managed GCE is not rendered yet`,
  );
};

const storageBlock = (s: EnrichedIR["storage"][number], ir: EnrichedIR): string => {
  const label = tfName(s.name);
  if (s.kind === "shared-volume" || s.kind === "local-volume") {
    throw new Error(
      `volume "${s.name}": Filestore rendering deferred (costly abstraction) — mount S3/GCS or add a TODO issue`,
    );
  }
  return `resource "google_storage_bucket" "${label}" {
  name          = "${tfName(ir.meta.name)}-${label}"
  location      = var.region
  force_destroy = false

  uniform_bucket_level_access = true
}`;
};

const outputsTf = (ir: EnrichedIR): string => {
  const lines: string[] = [];
  // Only web units render as services with a URI; workers/cron render as jobs.
  for (const u of ir.compute.filter((c) => c.kind === "web")) {
    lines.push(`output "service_${tfName(u.name)}_url" {
  value = google_cloud_run_v2_service.${tfName(u.name)}.uri
}`);
  }
  for (const d of ir.datastores) {
    if (d.engine === "postgres" || d.engine === "mysql") {
      lines.push(`output "db_${tfName(d.name)}_ip" {
  value = google_sql_database_instance.${tfName(d.name)}.private_ip_address
}`);
    } else if (d.engine === "redis") {
      lines.push(`output "cache_${tfName(d.name)}_host" {
  value = google_redis_instance.${tfName(d.name)}.host
}`);
    }
  }
  for (const s of ir.storage) {
    if (s.kind === "static-assets" || s.kind === "uploads") {
      lines.push(`output "bucket_${tfName(s.name)}" {
  value = google_storage_bucket.${tfName(s.name)}.name
}`);
    }
  }
  return `${HEADER}${lines.join("\n\n")}`;
};

export function renderGcp(ir: EnrichedIR): RenderResult {
  const diagnostics: RenderResult["diagnostics"] = [];
  for (const d of ir.datastores.filter((d) => d.engine === "postgres" || d.engine === "mysql")) {
    diagnostics.push(...resolveDatabaseVersion("gcp", d).diagnostics);
  }
  for (const u of ir.compute) {
    for (const key of new Set(u.secrets)) {
      diagnostics.push({
        stage: "render",
        severity: "warning",
        message: `service ${quote(u.name)} secret ${quote(key)} requires manual Secret Manager injection into Cloud Run`,
      });
    }
  }

  const dupError = duplicateLabelError(ir.compute.map((u) => u.name));
  if (dupError !== undefined) {
    diagnostics.push({ stage: "render", severity: "error", message: dupError });
  }

  // Every public port that won't be exposed must be visible to the user.
  for (const unit of ir.compute.filter((u) => u.kind !== "stateful")) {
    const publicPorts = unit.ports.filter((p) => p.public);
    const served = unit.kind === "web" ? publicPorts.find((p) => p.protocol === "tcp") : undefined;
    for (const port of publicPorts) {
      if (port === served) continue;
      const reason =
        port.protocol === "udp"
          ? "UDP is not supported by Cloud Run ingress"
          : unit.kind !== "web"
            ? "Cloud Run jobs have no ingress"
            : "Cloud Run services support a single container port";
      diagnostics.push({
        stage: "render",
        severity: "warning",
        message: `${quote(unit.name)}:${port.container}/${port.protocol} not exposed: ${reason}; route this port separately`,
      });
    }
  }

  const network = renderSections([{ name: "network", builder: networkSection }], ir);
  const compute =
    dupError !== undefined
      ? { content: "", diagnostics: [] }
      : renderSections(
          [
            { name: "cloud-run", builder: computeSection },
            { name: "stateful", builder: statefulSection },
          ],
          ir,
        );
  const data = renderSections(
    [
      ...ir.datastores.map((d) => ({
        name: `datastore-${d.name}`,
        builder: () => datastoreBlock(d),
      })),
      ...ir.storage.map((s) => ({ name: `storage-${s.name}`, builder: () => storageBlock(s, ir) })),
    ],
    ir,
  );
  diagnostics.push(...network.diagnostics, ...compute.diagnostics, ...data.diagnostics);

  return {
    files: {
      "providers.tf": providersTf(),
      "variables.tf": variablesTf(ir),
      "network.tf": `${HEADER}${network.content}`,
      "compute.tf": `${HEADER}${dupError !== undefined ? `# TODO(dodeploy): ${dupError}\n` : compute.content}`,
      "data.tf": `${HEADER}${data.content}`,
      "outputs.tf": outputsTf(ir),
    },
    diagnostics,
  };
}
